default_platform(:android)

platform :android do
  desc "Upload Play Store listing metadata (no APK/AAB)"
  lane :update_listing do
    supply(
      track: "production",
      metadata_path: "fastlane/metadata/android",
      skip_upload_apk: true,
      skip_upload_aab: true,
      skip_upload_metadata: false,
      skip_upload_changelogs: false,
      skip_upload_images: true,
      skip_upload_screenshots: true
    )
  end
end
