package com.typlx.keyboard.ui

data class EmojiEntry(val emoji: String, val name: String)

enum class EmojiCategory(val displayName: String, val icon: String) {
    SMILEYS("Smileys", "😊"),
    PEOPLE("People", "👋"),
    ANIMALS("Animals", "🐶"),
    FOOD("Food", "🍎"),
    TRAVEL("Travel", "✈️"),
    ACTIVITIES("Activities", "⚽"),
    OBJECTS("Objects", "💡"),
    SYMBOLS("Symbols", "❤️"),
}

val EMOJI_DATA: Map<EmojiCategory, List<EmojiEntry>> = mapOf(
    EmojiCategory.SMILEYS to listOf(
        EmojiEntry("😀", "grinning face"),
        EmojiEntry("😃", "grinning face with big eyes"),
        EmojiEntry("😄", "grinning face with smiling eyes"),
        EmojiEntry("😁", "beaming face"),
        EmojiEntry("😆", "grinning squinting face"),
        EmojiEntry("😅", "grinning face with sweat"),
        EmojiEntry("🤣", "rolling on the floor laughing"),
        EmojiEntry("😂", "face with tears of joy"),
        EmojiEntry("🙂", "slightly smiling face"),
        EmojiEntry("🙃", "upside-down face"),
        EmojiEntry("😊", "smiling face with smiling eyes"),
        EmojiEntry("😇", "smiling face with halo"),
        EmojiEntry("🥰", "smiling face with hearts"),
        EmojiEntry("😍", "smiling face with heart-eyes"),
        EmojiEntry("🤩", "star-struck"),
        EmojiEntry("😘", "face blowing a kiss"),
        EmojiEntry("😗", "kissing face"),
        EmojiEntry("😚", "kissing face with closed eyes"),
        EmojiEntry("😙", "kissing face with smiling eyes"),
        EmojiEntry("🥲", "smiling face with tear"),
        EmojiEntry("😋", "face savoring food"),
        EmojiEntry("😛", "face with tongue"),
        EmojiEntry("😜", "winking face with tongue"),
        EmojiEntry("🤪", "zany face"),
        EmojiEntry("😝", "squinting face with tongue"),
        EmojiEntry("🤑", "money-mouth face"),
        EmojiEntry("🤗", "hugging face"),
        EmojiEntry("🤭", "face with hand over mouth"),
        EmojiEntry("🤫", "shushing face"),
        EmojiEntry("🤔", "thinking face"),
        EmojiEntry("😐", "neutral face"),
        EmojiEntry("😑", "expressionless face"),
        EmojiEntry("😶", "face without mouth"),
        EmojiEntry("😏", "smirking face"),
        EmojiEntry("😒", "unamused face"),
        EmojiEntry("🙄", "face with rolling eyes"),
        EmojiEntry("😬", "grimacing face"),
        EmojiEntry("🤥", "lying face"),
        EmojiEntry("😌", "relieved face"),
        EmojiEntry("😔", "pensive face"),
        EmojiEntry("😪", "sleepy face"),
        EmojiEntry("🤤", "drooling face"),
        EmojiEntry("😴", "sleeping face"),
        EmojiEntry("😷", "face with medical mask"),
        EmojiEntry("🤒", "face with thermometer"),
        EmojiEntry("🤕", "face with head-bandage"),
        EmojiEntry("🤢", "nauseated face"),
        EmojiEntry("🤧", "sneezing face"),
        EmojiEntry("🥵", "hot face"),
        EmojiEntry("🥶", "cold face"),
        EmojiEntry("🥴", "woozy face"),
        EmojiEntry("😵", "dizzy face"),
        EmojiEntry("🤯", "exploding head"),
        EmojiEntry("🤠", "cowboy hat face"),
        EmojiEntry("🥳", "partying face"),
        EmojiEntry("😎", "smiling face with sunglasses"),
        EmojiEntry("🤓", "nerd face"),
        EmojiEntry("🧐", "face with monocle"),
        EmojiEntry("😕", "confused face"),
        EmojiEntry("😟", "worried face"),
        EmojiEntry("🙁", "slightly frowning face"),
        EmojiEntry("😮", "face with open mouth"),
        EmojiEntry("😯", "hushed face"),
        EmojiEntry("😲", "astonished face"),
        EmojiEntry("😳", "flushed face"),
        EmojiEntry("🥺", "pleading face"),
        EmojiEntry("😦", "frowning face with open mouth"),
        EmojiEntry("😧", "anguished face"),
        EmojiEntry("😨", "fearful face"),
        EmojiEntry("😰", "anxious face with sweat"),
        EmojiEntry("😥", "sad but relieved face"),
        EmojiEntry("😢", "crying face"),
        EmojiEntry("😭", "loudly crying face"),
        EmojiEntry("😱", "screaming in fear"),
        EmojiEntry("😖", "confounded face"),
        EmojiEntry("😣", "persevering face"),
        EmojiEntry("😞", "disappointed face"),
        EmojiEntry("😓", "downcast face with sweat"),
        EmojiEntry("😩", "weary face"),
        EmojiEntry("😫", "tired face"),
        EmojiEntry("🥱", "yawning face"),
        EmojiEntry("😤", "face with steam from nose"),
        EmojiEntry("😡", "pouting face"),
        EmojiEntry("😠", "angry face"),
        EmojiEntry("🤬", "face with symbols on mouth"),
        EmojiEntry("😈", "smiling face with horns"),
        EmojiEntry("👿", "angry face with horns"),
        EmojiEntry("💀", "skull"),
        EmojiEntry("☠️", "skull and crossbones"),
        EmojiEntry("💩", "pile of poo"),
        EmojiEntry("🤡", "clown face"),
        EmojiEntry("👹", "ogre"),
        EmojiEntry("👺", "goblin"),
        EmojiEntry("👻", "ghost"),
        EmojiEntry("👾", "alien monster"),
        EmojiEntry("🤖", "robot"),
        EmojiEntry("😺", "grinning cat"),
        EmojiEntry("😸", "grinning cat with smiling eyes"),
        EmojiEntry("😹", "cat with tears of joy"),
        EmojiEntry("😻", "smiling cat with heart-eyes"),
        EmojiEntry("😼", "cat with wry smile"),
        EmojiEntry("😽", "kissing cat"),
        EmojiEntry("🙀", "weary cat"),
        EmojiEntry("😿", "crying cat"),
        EmojiEntry("😾", "pouting cat"),
    ),
    EmojiCategory.PEOPLE to listOf(
        EmojiEntry("👋", "waving hand"),
        EmojiEntry("🤚", "raised back of hand"),
        EmojiEntry("🖐️", "hand with fingers splayed"),
        EmojiEntry("✋", "raised hand"),
        EmojiEntry("🖖", "vulcan salute"),
        EmojiEntry("👌", "ok hand"),
        EmojiEntry("🤌", "pinched fingers"),
        EmojiEntry("✌️", "victory hand"),
        EmojiEntry("🤞", "crossed fingers"),
        EmojiEntry("🤟", "love-you gesture"),
        EmojiEntry("🤘", "sign of the horns"),
        EmojiEntry("🤙", "call me hand"),
        EmojiEntry("👈", "backhand index pointing left"),
        EmojiEntry("👉", "backhand index pointing right"),
        EmojiEntry("👆", "backhand index pointing up"),
        EmojiEntry("🖕", "middle finger"),
        EmojiEntry("👇", "backhand index pointing down"),
        EmojiEntry("☝️", "index pointing up"),
        EmojiEntry("👍", "thumbs up"),
        EmojiEntry("👎", "thumbs down"),
        EmojiEntry("✊", "raised fist"),
        EmojiEntry("👊", "oncoming fist"),
        EmojiEntry("🤛", "left-facing fist"),
        EmojiEntry("🤜", "right-facing fist"),
        EmojiEntry("👏", "clapping hands"),
        EmojiEntry("🙌", "raising hands"),
        EmojiEntry("👐", "open hands"),
        EmojiEntry("🤲", "palms up together"),
        EmojiEntry("🤝", "handshake"),
        EmojiEntry("🙏", "folded hands"),
        EmojiEntry("💪", "flexed biceps"),
        EmojiEntry("🦾", "mechanical arm"),
        EmojiEntry("🦿", "mechanical leg"),
        EmojiEntry("🦵", "leg"),
        EmojiEntry("🦶", "foot"),
        EmojiEntry("👂", "ear"),
        EmojiEntry("🦻", "ear with hearing aid"),
        EmojiEntry("👃", "nose"),
        EmojiEntry("👀", "eyes"),
        EmojiEntry("👁️", "eye"),
        EmojiEntry("👅", "tongue"),
        EmojiEntry("👄", "mouth"),
        EmojiEntry("🧠", "brain"),
        EmojiEntry("🦷", "tooth"),
        EmojiEntry("🦴", "bone"),
        EmojiEntry("👣", "footprints"),
        EmojiEntry("🧑", "person"),
        EmojiEntry("👦", "boy"),
        EmojiEntry("👧", "girl"),
        EmojiEntry("👨", "man"),
        EmojiEntry("👩", "woman"),
        EmojiEntry("🧓", "older person"),
        EmojiEntry("👴", "old man"),
        EmojiEntry("👵", "old woman"),
        EmojiEntry("👶", "baby"),
        EmojiEntry("🧒", "child"),
        EmojiEntry("👼", "baby angel"),
        EmojiEntry("🤶", "Mrs. Claus"),
        EmojiEntry("🎅", "Santa Claus"),
        EmojiEntry("🧙", "mage"),
        EmojiEntry("🦸", "superhero"),
        EmojiEntry("🦹", "supervillain"),
        EmojiEntry("💆", "person getting massage"),
        EmojiEntry("💇", "person getting haircut"),
        EmojiEntry("🚶", "person walking"),
        EmojiEntry("🧍", "person standing"),
        EmojiEntry("🧎", "person kneeling"),
        EmojiEntry("🏃", "person running"),
        EmojiEntry("💃", "woman dancing"),
        EmojiEntry("🕺", "man dancing"),
        EmojiEntry("🕴️", "person in suit levitating"),
        EmojiEntry("👯", "people with bunny ears"),
        EmojiEntry("🧖", "person in steamy room"),
        EmojiEntry("🛀", "person taking bath"),
        EmojiEntry("👤", "bust in silhouette"),
        EmojiEntry("👥", "busts in silhouette"),
        EmojiEntry("🫂", "people hugging"),
        EmojiEntry("👨‍👩‍👧‍👦", "family"),
        EmojiEntry("💑", "couple with heart"),
        EmojiEntry("💏", "kiss"),
    ),
    EmojiCategory.ANIMALS to listOf(
        EmojiEntry("🐶", "dog face"),
        EmojiEntry("🐱", "cat face"),
        EmojiEntry("🐭", "mouse face"),
        EmojiEntry("🐹", "hamster"),
        EmojiEntry("🐰", "rabbit face"),
        EmojiEntry("🦊", "fox"),
        EmojiEntry("🐻", "bear"),
        EmojiEntry("🐼", "panda"),
        EmojiEntry("🐨", "koala"),
        EmojiEntry("🐯", "tiger face"),
        EmojiEntry("🦁", "lion"),
        EmojiEntry("🐮", "cow face"),
        EmojiEntry("🐷", "pig face"),
        EmojiEntry("🐸", "frog"),
        EmojiEntry("🐵", "monkey face"),
        EmojiEntry("🙈", "see-no-evil monkey"),
        EmojiEntry("🙉", "hear-no-evil monkey"),
        EmojiEntry("🙊", "speak-no-evil monkey"),
        EmojiEntry("🐔", "chicken"),
        EmojiEntry("🐧", "penguin"),
        EmojiEntry("🐦", "bird"),
        EmojiEntry("🦆", "duck"),
        EmojiEntry("🦅", "eagle"),
        EmojiEntry("🦉", "owl"),
        EmojiEntry("🦇", "bat"),
        EmojiEntry("🐺", "wolf"),
        EmojiEntry("🐗", "boar"),
        EmojiEntry("🐴", "horse face"),
        EmojiEntry("🦄", "unicorn"),
        EmojiEntry("🐝", "honeybee"),
        EmojiEntry("🐛", "bug"),
        EmojiEntry("🦋", "butterfly"),
        EmojiEntry("🐌", "snail"),
        EmojiEntry("🐞", "lady beetle"),
        EmojiEntry("🐜", "ant"),
        EmojiEntry("🦟", "mosquito"),
        EmojiEntry("🦗", "cricket"),
        EmojiEntry("🕷️", "spider"),
        EmojiEntry("🦂", "scorpion"),
        EmojiEntry("🐢", "turtle"),
        EmojiEntry("🐍", "snake"),
        EmojiEntry("🦎", "lizard"),
        EmojiEntry("🦖", "T-Rex"),
        EmojiEntry("🐊", "crocodile"),
        EmojiEntry("🦈", "shark"),
        EmojiEntry("🐙", "octopus"),
        EmojiEntry("🦑", "squid"),
        EmojiEntry("🦞", "lobster"),
        EmojiEntry("🐠", "tropical fish"),
        EmojiEntry("🐟", "fish"),
        EmojiEntry("🐬", "dolphin"),
        EmojiEntry("🐳", "spouting whale"),
        EmojiEntry("🦭", "seal"),
        EmojiEntry("🐘", "elephant"),
        EmojiEntry("🦏", "rhinoceros"),
        EmojiEntry("🦒", "giraffe"),
        EmojiEntry("🦓", "zebra"),
        EmojiEntry("🦛", "hippopotamus"),
        EmojiEntry("🐪", "camel"),
        EmojiEntry("🦘", "kangaroo"),
        EmojiEntry("🦥", "sloth"),
        EmojiEntry("🦦", "otter"),
        EmojiEntry("🦨", "skunk"),
        EmojiEntry("🦡", "badger"),
        EmojiEntry("🐾", "paw prints"),
        EmojiEntry("🌿", "herb"),
        EmojiEntry("🌱", "seedling"),
        EmojiEntry("🌲", "evergreen tree"),
        EmojiEntry("🌳", "deciduous tree"),
        EmojiEntry("🌴", "palm tree"),
        EmojiEntry("🌵", "cactus"),
        EmojiEntry("🌾", "sheaf of rice"),
        EmojiEntry("☘️", "shamrock"),
        EmojiEntry("🍀", "four leaf clover"),
        EmojiEntry("🎋", "tanabata tree"),
        EmojiEntry("🎍", "pine decoration"),
        EmojiEntry("🍁", "maple leaf"),
        EmojiEntry("🍂", "fallen leaf"),
        EmojiEntry("🍃", "leaf fluttering in wind"),
        EmojiEntry("🌺", "hibiscus"),
        EmojiEntry("🌸", "cherry blossom"),
        EmojiEntry("🌼", "blossom"),
        EmojiEntry("🌻", "sunflower"),
        EmojiEntry("🌹", "rose"),
        EmojiEntry("🌷", "tulip"),
        EmojiEntry("💐", "bouquet"),
        EmojiEntry("🌙", "crescent moon"),
        EmojiEntry("⭐", "star"),
        EmojiEntry("🌟", "glowing star"),
        EmojiEntry("☀️", "sun"),
        EmojiEntry("🌈", "rainbow"),
        EmojiEntry("⛅", "sun behind cloud"),
        EmojiEntry("🌩️", "cloud with lightning"),
        EmojiEntry("🌧️", "cloud with rain"),
        EmojiEntry("❄️", "snowflake"),
        EmojiEntry("🌊", "water wave"),
        EmojiEntry("🔥", "fire"),
        EmojiEntry("💧", "droplet"),
        EmojiEntry("🌍", "globe showing Europe-Africa"),
        EmojiEntry("🌎", "globe showing Americas"),
        EmojiEntry("🌏", "globe showing Asia-Australia"),
    ),
    EmojiCategory.FOOD to listOf(
        EmojiEntry("🍎", "red apple"),
        EmojiEntry("🍊", "tangerine"),
        EmojiEntry("🍋", "lemon"),
        EmojiEntry("🍇", "grapes"),
        EmojiEntry("🍓", "strawberry"),
        EmojiEntry("🫐", "blueberries"),
        EmojiEntry("🍈", "melon"),
        EmojiEntry("🍉", "watermelon"),
        EmojiEntry("🍑", "peach"),
        EmojiEntry("🍒", "cherries"),
        EmojiEntry("🍌", "banana"),
        EmojiEntry("🍍", "pineapple"),
        EmojiEntry("🥭", "mango"),
        EmojiEntry("🥝", "kiwi fruit"),
        EmojiEntry("🍅", "tomato"),
        EmojiEntry("🫒", "olive"),
        EmojiEntry("🥥", "coconut"),
        EmojiEntry("🥑", "avocado"),
        EmojiEntry("🍆", "eggplant"),
        EmojiEntry("🥔", "potato"),
        EmojiEntry("🥕", "carrot"),
        EmojiEntry("🌽", "ear of corn"),
        EmojiEntry("🌶️", "hot pepper"),
        EmojiEntry("🫑", "bell pepper"),
        EmojiEntry("🥦", "broccoli"),
        EmojiEntry("🧅", "onion"),
        EmojiEntry("🧄", "garlic"),
        EmojiEntry("🥜", "peanuts"),
        EmojiEntry("🫘", "beans"),
        EmojiEntry("🌰", "chestnut"),
        EmojiEntry("🍞", "bread"),
        EmojiEntry("🥐", "croissant"),
        EmojiEntry("🥨", "pretzel"),
        EmojiEntry("🧀", "cheese wedge"),
        EmojiEntry("🥚", "egg"),
        EmojiEntry("🍳", "cooking"),
        EmojiEntry("🧈", "butter"),
        EmojiEntry("🥞", "pancakes"),
        EmojiEntry("🧇", "waffle"),
        EmojiEntry("🥓", "bacon"),
        EmojiEntry("🥩", "cut of meat"),
        EmojiEntry("🍗", "poultry leg"),
        EmojiEntry("🍖", "meat on bone"),
        EmojiEntry("🌭", "hot dog"),
        EmojiEntry("🍔", "hamburger"),
        EmojiEntry("🍟", "french fries"),
        EmojiEntry("🍕", "pizza"),
        EmojiEntry("🌮", "taco"),
        EmojiEntry("🌯", "burrito"),
        EmojiEntry("🥗", "green salad"),
        EmojiEntry("🥘", "shallow pan of food"),
        EmojiEntry("🍝", "spaghetti"),
        EmojiEntry("🍜", "steaming bowl"),
        EmojiEntry("🍲", "pot of food"),
        EmojiEntry("🍛", "curry rice"),
        EmojiEntry("🍣", "sushi"),
        EmojiEntry("🍱", "bento box"),
        EmojiEntry("🍦", "soft ice cream"),
        EmojiEntry("🍧", "shaved ice"),
        EmojiEntry("🍨", "ice cream"),
        EmojiEntry("🍩", "doughnut"),
        EmojiEntry("🍪", "cookie"),
        EmojiEntry("🎂", "birthday cake"),
        EmojiEntry("🍰", "shortcake"),
        EmojiEntry("🧁", "cupcake"),
        EmojiEntry("🍫", "chocolate bar"),
        EmojiEntry("🍬", "candy"),
        EmojiEntry("🍭", "lollipop"),
        EmojiEntry("🍮", "custard"),
        EmojiEntry("🍯", "honey pot"),
        EmojiEntry("☕", "hot beverage"),
        EmojiEntry("🍵", "teacup without handle"),
        EmojiEntry("🧃", "beverage box"),
        EmojiEntry("🍶", "sake"),
        EmojiEntry("🍺", "beer mug"),
        EmojiEntry("🍻", "clinking beer mugs"),
        EmojiEntry("🥂", "clinking glasses"),
        EmojiEntry("🍷", "wine glass"),
        EmojiEntry("🥃", "tumbler glass"),
        EmojiEntry("🍸", "cocktail glass"),
        EmojiEntry("🍹", "tropical drink"),
        EmojiEntry("🧉", "mate"),
        EmojiEntry("🍾", "bottle with popping cork"),
        EmojiEntry("🧊", "ice"),
        EmojiEntry("🥄", "spoon"),
        EmojiEntry("🍴", "fork and knife"),
    ),
    EmojiCategory.TRAVEL to listOf(
        EmojiEntry("🚗", "automobile"),
        EmojiEntry("🚕", "taxi"),
        EmojiEntry("🚙", "sport utility vehicle"),
        EmojiEntry("🚌", "bus"),
        EmojiEntry("🚎", "trolleybus"),
        EmojiEntry("🏎️", "racing car"),
        EmojiEntry("🚓", "police car"),
        EmojiEntry("🚑", "ambulance"),
        EmojiEntry("🚒", "fire engine"),
        EmojiEntry("🚐", "minibus"),
        EmojiEntry("🛻", "pickup truck"),
        EmojiEntry("🚚", "delivery truck"),
        EmojiEntry("🚛", "articulated lorry"),
        EmojiEntry("🚜", "tractor"),
        EmojiEntry("🏍️", "motorcycle"),
        EmojiEntry("🛵", "motor scooter"),
        EmojiEntry("🚲", "bicycle"),
        EmojiEntry("🛴", "kick scooter"),
        EmojiEntry("🛹", "skateboard"),
        EmojiEntry("🚏", "bus stop"),
        EmojiEntry("⛽", "fuel pump"),
        EmojiEntry("🚦", "vertical traffic light"),
        EmojiEntry("🚥", "horizontal traffic light"),
        EmojiEntry("🚧", "construction"),
        EmojiEntry("🚂", "locomotive"),
        EmojiEntry("🚃", "railway car"),
        EmojiEntry("🚄", "high-speed train"),
        EmojiEntry("🚅", "bullet train"),
        EmojiEntry("🚆", "train"),
        EmojiEntry("🚇", "metro"),
        EmojiEntry("🚈", "light rail"),
        EmojiEntry("🚉", "station"),
        EmojiEntry("🚊", "tram"),
        EmojiEntry("🚞", "mountain railway"),
        EmojiEntry("✈️", "airplane"),
        EmojiEntry("🛫", "airplane departure"),
        EmojiEntry("🛬", "airplane arrival"),
        EmojiEntry("🪂", "parachute"),
        EmojiEntry("💺", "seat"),
        EmojiEntry("🚁", "helicopter"),
        EmojiEntry("🛸", "flying saucer"),
        EmojiEntry("🚀", "rocket"),
        EmojiEntry("⛵", "sailboat"),
        EmojiEntry("🚤", "speedboat"),
        EmojiEntry("🛥️", "motor boat"),
        EmojiEntry("🚢", "ship"),
        EmojiEntry("⛴️", "ferry"),
        EmojiEntry("🌐", "globe with meridians"),
        EmojiEntry("🗺️", "world map"),
        EmojiEntry("🧭", "compass"),
        EmojiEntry("⛰️", "mountain"),
        EmojiEntry("🏔️", "snow-capped mountain"),
        EmojiEntry("🗻", "mount fuji"),
        EmojiEntry("🏕️", "camping"),
        EmojiEntry("🏖️", "beach with umbrella"),
        EmojiEntry("🏜️", "desert"),
        EmojiEntry("🏝️", "desert island"),
        EmojiEntry("🏞️", "national park"),
        EmojiEntry("🏟️", "stadium"),
        EmojiEntry("🏛️", "classical building"),
        EmojiEntry("🏗️", "building construction"),
        EmojiEntry("🏠", "house"),
        EmojiEntry("🏡", "house with garden"),
        EmojiEntry("🏢", "office building"),
        EmojiEntry("🏣", "Japanese post office"),
        EmojiEntry("🏥", "hospital"),
        EmojiEntry("🏦", "bank"),
        EmojiEntry("🏨", "hotel"),
        EmojiEntry("🏩", "love hotel"),
        EmojiEntry("🏪", "convenience store"),
        EmojiEntry("🏫", "school"),
        EmojiEntry("🏬", "department store"),
        EmojiEntry("🏭", "factory"),
        EmojiEntry("🗼", "Tokyo tower"),
        EmojiEntry("🗽", "Statue of Liberty"),
        EmojiEntry("⛪", "church"),
        EmojiEntry("🕌", "mosque"),
        EmojiEntry("🛕", "hindu temple"),
        EmojiEntry("🕍", "synagogue"),
        EmojiEntry("⛩️", "shinto shrine"),
        EmojiEntry("🌁", "foggy"),
        EmojiEntry("🌃", "night with stars"),
        EmojiEntry("🌄", "sunrise over mountains"),
        EmojiEntry("🌅", "sunrise"),
        EmojiEntry("🌆", "cityscape at dusk"),
        EmojiEntry("🌇", "sunset"),
        EmojiEntry("🌉", "bridge at night"),
        EmojiEntry("🗾", "map of Japan"),
        EmojiEntry("🎑", "moon viewing ceremony"),
    ),
    EmojiCategory.ACTIVITIES to listOf(
        EmojiEntry("⚽", "soccer ball"),
        EmojiEntry("🏀", "basketball"),
        EmojiEntry("🏈", "american football"),
        EmojiEntry("⚾", "baseball"),
        EmojiEntry("🥎", "softball"),
        EmojiEntry("🎾", "tennis"),
        EmojiEntry("🏐", "volleyball"),
        EmojiEntry("🏉", "rugby football"),
        EmojiEntry("🥏", "flying disc"),
        EmojiEntry("🎱", "pool 8 ball"),
        EmojiEntry("🏓", "ping pong"),
        EmojiEntry("🏸", "badminton"),
        EmojiEntry("🥊", "boxing glove"),
        EmojiEntry("🥋", "martial arts uniform"),
        EmojiEntry("🥅", "goal net"),
        EmojiEntry("⛳", "flag in hole"),
        EmojiEntry("🏹", "bow and arrow"),
        EmojiEntry("🎣", "fishing pole"),
        EmojiEntry("🤿", "diving mask"),
        EmojiEntry("🎽", "running shirt"),
        EmojiEntry("🎿", "skis"),
        EmojiEntry("🛷", "sled"),
        EmojiEntry("🥌", "curling stone"),
        EmojiEntry("🏋️", "person lifting weights"),
        EmojiEntry("🤼", "people wrestling"),
        EmojiEntry("🤸", "person cartwheeling"),
        EmojiEntry("🤺", "person fencing"),
        EmojiEntry("🏇", "horse racing"),
        EmojiEntry("⛷️", "skier"),
        EmojiEntry("🏂", "snowboarder"),
        EmojiEntry("🪂", "parachute"),
        EmojiEntry("🏌️", "person golfing"),
        EmojiEntry("🏄", "person surfing"),
        EmojiEntry("🚣", "person rowing boat"),
        EmojiEntry("🧗", "person climbing"),
        EmojiEntry("🚵", "person mountain biking"),
        EmojiEntry("🚴", "person biking"),
        EmojiEntry("🏊", "person swimming"),
        EmojiEntry("🤽", "person playing water polo"),
        EmojiEntry("🏇", "horse racing"),
        EmojiEntry("🧘", "person in lotus position"),
        EmojiEntry("🎮", "video game"),
        EmojiEntry("🕹️", "joystick"),
        EmojiEntry("🎯", "bullseye"),
        EmojiEntry("🎳", "bowling"),
        EmojiEntry("🧩", "puzzle piece"),
        EmojiEntry("🎲", "game die"),
        EmojiEntry("♟️", "chess pawn"),
        EmojiEntry("🎭", "performing arts"),
        EmojiEntry("🎨", "artist palette"),
        EmojiEntry("🎬", "clapper board"),
        EmojiEntry("🎤", "microphone"),
        EmojiEntry("🎧", "headphone"),
        EmojiEntry("🎼", "musical score"),
        EmojiEntry("🎵", "musical note"),
        EmojiEntry("🎶", "musical notes"),
        EmojiEntry("🎷", "saxophone"),
        EmojiEntry("🎸", "guitar"),
        EmojiEntry("🎹", "musical keyboard"),
        EmojiEntry("🎺", "trumpet"),
        EmojiEntry("🎻", "violin"),
        EmojiEntry("🥁", "drum"),
        EmojiEntry("🎙️", "studio microphone"),
        EmojiEntry("📻", "radio"),
        EmojiEntry("📺", "television"),
        EmojiEntry("🎞️", "film frames"),
        EmojiEntry("🎟️", "admission tickets"),
        EmojiEntry("🎪", "circus tent"),
        EmojiEntry("🎠", "carousel horse"),
        EmojiEntry("🎡", "ferris wheel"),
        EmojiEntry("🎢", "roller coaster"),
        EmojiEntry("🎈", "balloon"),
        EmojiEntry("🎆", "fireworks"),
        EmojiEntry("🎇", "sparkler"),
        EmojiEntry("🧨", "firecracker"),
        EmojiEntry("🎉", "party popper"),
        EmojiEntry("🎊", "confetti ball"),
        EmojiEntry("🎋", "tanabata tree"),
        EmojiEntry("🎍", "pine decoration"),
        EmojiEntry("🎎", "Japanese dolls"),
        EmojiEntry("🎏", "carp streamer"),
        EmojiEntry("🎐", "wind chime"),
        EmojiEntry("🎑", "moon viewing ceremony"),
        EmojiEntry("🧧", "red envelope"),
        EmojiEntry("🎀", "ribbon"),
        EmojiEntry("🎁", "wrapped gift"),
        EmojiEntry("🏆", "trophy"),
        EmojiEntry("🥇", "1st place medal"),
        EmojiEntry("🥈", "2nd place medal"),
        EmojiEntry("🥉", "3rd place medal"),
        EmojiEntry("🎖️", "military medal"),
        EmojiEntry("🏅", "sports medal"),
    ),
    EmojiCategory.OBJECTS to listOf(
        EmojiEntry("💡", "light bulb"),
        EmojiEntry("🔦", "flashlight"),
        EmojiEntry("🕯️", "candle"),
        EmojiEntry("📱", "mobile phone"),
        EmojiEntry("💻", "laptop"),
        EmojiEntry("⌨️", "keyboard"),
        EmojiEntry("🖥️", "desktop computer"),
        EmojiEntry("🖨️", "printer"),
        EmojiEntry("🖱️", "computer mouse"),
        EmojiEntry("🖲️", "trackball"),
        EmojiEntry("💾", "floppy disk"),
        EmojiEntry("💿", "optical disk"),
        EmojiEntry("📷", "camera"),
        EmojiEntry("📸", "camera with flash"),
        EmojiEntry("📹", "video camera"),
        EmojiEntry("🎥", "movie camera"),
        EmojiEntry("📞", "telephone receiver"),
        EmojiEntry("☎️", "telephone"),
        EmojiEntry("📟", "pager"),
        EmojiEntry("📠", "fax machine"),
        EmojiEntry("📺", "television"),
        EmojiEntry("📻", "radio"),
        EmojiEntry("⏰", "alarm clock"),
        EmojiEntry("⌚", "watch"),
        EmojiEntry("⏱️", "stopwatch"),
        EmojiEntry("⏲️", "timer clock"),
        EmojiEntry("🕰️", "mantelpiece clock"),
        EmojiEntry("📡", "satellite antenna"),
        EmojiEntry("🔋", "battery"),
        EmojiEntry("🔌", "electric plug"),
        EmojiEntry("🔍", "magnifying glass tilted left"),
        EmojiEntry("🔎", "magnifying glass tilted right"),
        EmojiEntry("🔒", "locked"),
        EmojiEntry("🔓", "unlocked"),
        EmojiEntry("🔑", "key"),
        EmojiEntry("🗝️", "old key"),
        EmojiEntry("🔨", "hammer"),
        EmojiEntry("🪓", "axe"),
        EmojiEntry("⛏️", "pick"),
        EmojiEntry("🔧", "wrench"),
        EmojiEntry("🔩", "nut and bolt"),
        EmojiEntry("🪛", "screwdriver"),
        EmojiEntry("🔫", "pistol"),
        EmojiEntry("💣", "bomb"),
        EmojiEntry("🧨", "firecracker"),
        EmojiEntry("🪤", "mouse trap"),
        EmojiEntry("🪜", "ladder"),
        EmojiEntry("🧲", "magnet"),
        EmojiEntry("🪣", "bucket"),
        EmojiEntry("🧴", "lotion bottle"),
        EmojiEntry("🧷", "safety pin"),
        EmojiEntry("🧹", "broom"),
        EmojiEntry("🧺", "basket"),
        EmojiEntry("🧻", "roll of paper"),
        EmojiEntry("🚽", "toilet"),
        EmojiEntry("🚿", "shower"),
        EmojiEntry("🛁", "bathtub"),
        EmojiEntry("🪒", "razor"),
        EmojiEntry("🪥", "toothbrush"),
        EmojiEntry("🧴", "lotion bottle"),
        EmojiEntry("💊", "pill"),
        EmojiEntry("💉", "syringe"),
        EmojiEntry("🩹", "adhesive bandage"),
        EmojiEntry("🩺", "stethoscope"),
        EmojiEntry("🩻", "x-ray"),
        EmojiEntry("📚", "books"),
        EmojiEntry("📖", "open book"),
        EmojiEntry("📝", "memo"),
        EmojiEntry("✏️", "pencil"),
        EmojiEntry("🖊️", "pen"),
        EmojiEntry("🖋️", "fountain pen"),
        EmojiEntry("📌", "pushpin"),
        EmojiEntry("📎", "paperclip"),
        EmojiEntry("✂️", "scissors"),
        EmojiEntry("🗑️", "wastebasket"),
        EmojiEntry("💰", "money bag"),
        EmojiEntry("💳", "credit card"),
        EmojiEntry("💵", "dollar banknote"),
        EmojiEntry("📦", "package"),
        EmojiEntry("📬", "open mailbox with mail"),
        EmojiEntry("📮", "postbox"),
        EmojiEntry("🛍️", "shopping bags"),
        EmojiEntry("🎒", "backpack"),
        EmojiEntry("👜", "handbag"),
        EmojiEntry("👝", "clutch bag"),
        EmojiEntry("👛", "purse"),
        EmojiEntry("👓", "glasses"),
        EmojiEntry("🕶️", "sunglasses"),
        EmojiEntry("🥽", "goggles"),
        EmojiEntry("🌂", "closed umbrella"),
        EmojiEntry("☂️", "umbrella"),
        EmojiEntry("🧵", "thread"),
        EmojiEntry("🪡", "sewing needle"),
        EmojiEntry("🧶", "yarn"),
        EmojiEntry("🪢", "knot"),
    ),
    EmojiCategory.SYMBOLS to listOf(
        EmojiEntry("❤️", "red heart"),
        EmojiEntry("🧡", "orange heart"),
        EmojiEntry("💛", "yellow heart"),
        EmojiEntry("💚", "green heart"),
        EmojiEntry("💙", "blue heart"),
        EmojiEntry("💜", "purple heart"),
        EmojiEntry("🖤", "black heart"),
        EmojiEntry("🤍", "white heart"),
        EmojiEntry("🤎", "brown heart"),
        EmojiEntry("💔", "broken heart"),
        EmojiEntry("❣️", "heart exclamation"),
        EmojiEntry("💕", "two hearts"),
        EmojiEntry("💞", "revolving hearts"),
        EmojiEntry("💓", "beating heart"),
        EmojiEntry("💗", "growing heart"),
        EmojiEntry("💖", "sparkling heart"),
        EmojiEntry("💘", "heart with arrow"),
        EmojiEntry("💝", "heart with ribbon"),
        EmojiEntry("💟", "heart decoration"),
        EmojiEntry("☮️", "peace symbol"),
        EmojiEntry("✝️", "latin cross"),
        EmojiEntry("☪️", "star and crescent"),
        EmojiEntry("🕉️", "om"),
        EmojiEntry("✡️", "star of David"),
        EmojiEntry("🔯", "dotted six-pointed star"),
        EmojiEntry("☯️", "yin yang"),
        EmojiEntry("🈳", "Japanese vacancy button"),
        EmojiEntry("🆗", "OK button"),
        EmojiEntry("🆙", "UP! button"),
        EmojiEntry("🆒", "COOL button"),
        EmojiEntry("🆕", "NEW button"),
        EmojiEntry("🆓", "FREE button"),
        EmojiEntry("🆖", "NG button"),
        EmojiEntry("🆘", "SOS button"),
        EmojiEntry("🆚", "VS button"),
        EmojiEntry("⛔", "no entry"),
        EmojiEntry("🚫", "prohibited"),
        EmojiEntry("🚳", "no bicycles"),
        EmojiEntry("🚭", "no smoking"),
        EmojiEntry("🚯", "no littering"),
        EmojiEntry("🚱", "non-potable water"),
        EmojiEntry("🔞", "no one under eighteen"),
        EmojiEntry("❌", "cross mark"),
        EmojiEntry("⭕", "hollow red circle"),
        EmojiEntry("✅", "check mark button"),
        EmojiEntry("☑️", "check box with check"),
        EmojiEntry("✔️", "check mark"),
        EmojiEntry("❎", "cross mark button"),
        EmojiEntry("🔀", "shuffle tracks button"),
        EmojiEntry("🔁", "repeat button"),
        EmojiEntry("🔂", "repeat single button"),
        EmojiEntry("▶️", "play button"),
        EmojiEntry("⏩", "fast-forward button"),
        EmojiEntry("⏭️", "next track button"),
        EmojiEntry("⏯️", "play or pause button"),
        EmojiEntry("◀️", "reverse button"),
        EmojiEntry("⏪", "fast reverse button"),
        EmojiEntry("⏮️", "last track button"),
        EmojiEntry("🔼", "upwards button"),
        EmojiEntry("⏫", "fast up button"),
        EmojiEntry("🔽", "downwards button"),
        EmojiEntry("⏬", "fast down button"),
        EmojiEntry("⏸️", "pause button"),
        EmojiEntry("⏹️", "stop button"),
        EmojiEntry("⏺️", "record button"),
        EmojiEntry("🎦", "cinema"),
        EmojiEntry("🔅", "dim button"),
        EmojiEntry("🔆", "bright button"),
        EmojiEntry("📶", "antenna bars"),
        EmojiEntry("📳", "vibration mode"),
        EmojiEntry("📴", "mobile phone off"),
        EmojiEntry("♀️", "female sign"),
        EmojiEntry("♂️", "male sign"),
        EmojiEntry("⚧️", "transgender symbol"),
        EmojiEntry("✖️", "multiply"),
        EmojiEntry("➕", "plus"),
        EmojiEntry("➖", "minus"),
        EmojiEntry("➗", "divide"),
        EmojiEntry("♾️", "infinity"),
        EmojiEntry("‼️", "double exclamation mark"),
        EmojiEntry("⁉️", "exclamation question mark"),
        EmojiEntry("❓", "red question mark"),
        EmojiEntry("❔", "white question mark"),
        EmojiEntry("❕", "white exclamation mark"),
        EmojiEntry("❗", "red exclamation mark"),
        EmojiEntry("💱", "currency exchange"),
        EmojiEntry("💲", "heavy dollar sign"),
        EmojiEntry("⚕️", "medical symbol"),
        EmojiEntry("♻️", "recycling symbol"),
        EmojiEntry("⚜️", "fleur-de-lis"),
        EmojiEntry("🔰", "Japanese symbol for beginner"),
        EmojiEntry("✨", "sparkles"),
        EmojiEntry("💫", "dizzy"),
        EmojiEntry("💥", "collision"),
        EmojiEntry("🔥", "fire"),
        EmojiEntry("🌀", "cyclone"),
        EmojiEntry("🌊", "water wave"),
        EmojiEntry("💨", "dashing away"),
        EmojiEntry("💦", "sweat droplets"),
        EmojiEntry("☁️", "cloud"),
        EmojiEntry("⚡", "high voltage"),
        EmojiEntry("🌈", "rainbow"),
        EmojiEntry("⭐", "star"),
        EmojiEntry("🌟", "glowing star"),
        EmojiEntry("💎", "gem stone"),
        EmojiEntry("🏳️", "white flag"),
        EmojiEntry("🏴", "black flag"),
        EmojiEntry("🚩", "triangular flag"),
        EmojiEntry("🎌", "crossed flags"),
        EmojiEntry("🏁", "chequered flag"),
    ),
)
