package com.typlx.keyboard

/**
 * On-device dictionary of common English typos. Fires on space press before the LLM grammar
 * pass — fixes obvious mistakes silently and immediately.
 */
class AutoCorrectManager {

    fun correct(word: String): String? {
        if (word.isEmpty()) return null
        val lower = word.lowercase()
        val correction = TYPO_DICT[lower] ?: return null
        if (correction == lower) return null
        return preserveCase(word, correction)
    }

    private fun preserveCase(original: String, correction: String): String {
        if (original.isEmpty() || correction.isEmpty()) return correction
        return when {
            original.all { it.isUpperCase() } -> correction.uppercase()
            original[0].isUpperCase() -> correction.replaceFirstChar { it.uppercase() }
            else -> correction
        }
    }

    companion object {
        internal val TYPO_DICT: Map<String, String> = run {
            val pairs = listOf(
                // a
                "abbout" to "about",
                "abotu" to "about",
                "accomodate" to "accommodate",
                "accomodation" to "accommodation",
                "acomplish" to "accomplish",
                "acording" to "according",
                "accross" to "across",
                "actualy" to "actually",
                "adress" to "address",
                "agian" to "again",
                "againt" to "against",
                "agin" to "again",
                "agressive" to "aggressive",
                "alot" to "a lot",
                "alread" to "already",
                "alreayd" to "already",
                "alrigth" to "alright",
                "alwasy" to "always",
                "adn" to "and",
                "anbd" to "and",
                "ahve" to "have",
                "amke" to "make",
                "annd" to "and",
                "annother" to "another",
                "anotehr" to "another",
                "apparantly" to "apparently",
                "appearence" to "appearance",
                "aquire" to "acquire",
                "arguement" to "argument",
                "arond" to "around",
                "arround" to "around",
                "arugment" to "argument",
                "aslo" to "also",
                "assisstant" to "assistant",
                "atleast" to "at least",
                "atthe" to "at the",
                "avaliable" to "available",
                "awya" to "away",
                // b
                "bcak" to "back",
                "beccause" to "because",
                "becasue" to "because",
                "becuase" to "because",
                "beeing" to "being",
                "befor" to "before",
                "beggin" to "begin",
                "beleive" to "believe",
                "belive" to "believe",
                "beutiful" to "beautiful",
                "bgin" to "begin",
                "buisness" to "business",
                "busness" to "business",
                "bussiness" to "business",
                // c
                "calender" to "calendar",
                "cahnge" to "change",
                "calse" to "false",
                "carefull" to "careful",
                "certian" to "certain",
                "changeing" to "changing",
                "cheif" to "chief",
                "comeing" to "coming",
                "comming" to "coming",
                "commited" to "committed",
                "completly" to "completely",
                "concious" to "conscious",
                "consious" to "conscious",
                "continous" to "continuous",
                "conveniant" to "convenient",
                "couldnt" to "couldn't",
                "coudn't" to "couldn't",
                // d
                "daes" to "does",
                "definately" to "definitely",
                "defintely" to "definitely",
                "definetly" to "definitely",
                "desicion" to "decision",
                "desireable" to "desirable",
                "develope" to "develop",
                "diffrent" to "different",
                "diference" to "difference",
                "doesnt" to "doesn't",
                "dont" to "don't",
                "duing" to "during",
                // e
                "eachother" to "each other",
                "eigth" to "eighth",
                "embarass" to "embarrass",
                "embarrased" to "embarrassed",
                "enviroment" to "environment",
                "enviorment" to "environment",
                "equiped" to "equipped",
                "equiptment" to "equipment",
                "especialy" to "especially",
                "everywere" to "everywhere",
                "exept" to "except",
                "exsit" to "exist",
                "existance" to "existence",
                "experiance" to "experience",
                "expierence" to "experience",
                "explaination" to "explanation",
                // f
                "familar" to "familiar",
                "fasle" to "false",
                "feild" to "field",
                "finaly" to "finally",
                "fianlly" to "finally",
                "finley" to "finally",
                "foriegn" to "foreign",
                "foriegner" to "foreigner",
                "forgeting" to "forgetting",
                "fourm" to "forum",
                "freind" to "friend",
                "frmo" to "from",
                "fromt" to "from",
                "fomr" to "from",
                "frend" to "friend",
                "futher" to "further",
                // g
                "geting" to "getting",
                "goign" to "going",
                "goverment" to "government",
                "govermnet" to "government",
                "grammer" to "grammar",
                "guarentee" to "guarantee",
                "guidence" to "guidance",
                // h
                "haerd" to "heard",
                "happend" to "happened",
                "hapened" to "happened",
                "happenes" to "happens",
                "haveing" to "having",
                "hearign" to "hearing",
                "heared" to "heard",
                "hight" to "height",
                "hir" to "her",
                "hismelf" to "himself",
                "homogenous" to "homogeneous",
                "housr" to "hours",
                // i
                "ie" to "i.e.",
                "ignorence" to "ignorance",
                "immeditaly" to "immediately",
                "immeditaely" to "immediately",
                "incidently" to "incidentally",
                "independant" to "independent",
                "indispensible" to "indispensable",
                "insted" to "instead",
                "inteligent" to "intelligent",
                "intresting" to "interesting",
                "intrested" to "interested",
                "isnt" to "isn't",
                "isnot" to "is not",
                "iwth" to "with",
                // j
                "jstu" to "just",
                "jsut" to "just",
                // k
                "knowlege" to "knowledge",
                "knwo" to "know",
                "knwos" to "knows",
                // l
                "layed" to "laid",
                "laerning" to "learning",
                "leanring" to "learning",
                "liek" to "like",
                "lern" to "learn",
                "libary" to "library",
                "litle" to "little",
                "loign" to "login",
                "lovley" to "lovely",
                // m
                "maintainance" to "maintenance",
                "maintanance" to "maintenance",
                "makeing" to "making",
                "marraige" to "marriage",
                "medecine" to "medicine",
                "memeber" to "member",
                "messege" to "message",
                "millenium" to "millennium",
                "mispell" to "misspell",
                "mroe" to "more",
                "mysefl" to "myself",
                "myslef" to "myself",
                // n
                "necesary" to "necessary",
                "necessery" to "necessary",
                "neigbor" to "neighbor",
                "nieghbor" to "neighbor",
                "noticable" to "noticeable",
                "nto" to "not",
                // o
                "ocasion" to "occasion",
                "occurence" to "occurrence",
                "occured" to "occurred",
                "occuring" to "occurring",
                "offical" to "official",
                "omision" to "omission",
                "onyl" to "only",
                "oppurtunity" to "opportunity",
                "orginize" to "organize",
                "orignally" to "originally",
                // p
                "particulary" to "particularly",
                "payed" to "paid",
                "peice" to "piece",
                "perse" to "per se",
                "persue" to "pursue",
                "phillipines" to "Philippines",
                "possesion" to "possession",
                "possiblity" to "possibility",
                "potatos" to "potatoes",
                "practicaly" to "practically",
                "preferance" to "preference",
                "prefered" to "preferred",
                "privelege" to "privilege",
                "priviledge" to "privilege",
                "probabily" to "probably",
                "probelm" to "problem",
                "prject" to "project",
                "puting" to "putting",
                // q
                "quesiton" to "question",
                "questoin" to "question",
                // r
                "realy" to "really",
                "realyl" to "really",
                "reccomend" to "recommend",
                "recieve" to "receive",
                "recieved" to "received",
                "relevent" to "relevant",
                "rember" to "remember",
                "remeber" to "remember",
                "reponsible" to "responsible",
                "requirment" to "requirement",
                "resposible" to "responsible",
                "restarant" to "restaurant",
                "retun" to "return",
                "rigth" to "right",
                // s
                "saidhe" to "said he",
                "sayd" to "said",
                "seperate" to "separate",
                "sepearte" to "separate",
                "shouldnt" to "shouldn't",
                "similer" to "similar",
                "sinse" to "since",
                "somwhere" to "somewhere",
                "speach" to "speech",
                "speling" to "spelling",
                "sucess" to "success",
                "successfull" to "successful",
                "sumary" to "summary",
                "suprise" to "surprise",
                "suprsie" to "surprise",
                // t
                "tahn" to "than",
                "taht" to "that",
                "teh" to "the",
                "tghe" to "the",
                "therfore" to "therefore",
                "thier" to "their",
                "thign" to "thing",
                "thikning" to "thinking",
                "thinkign" to "thinking",
                "thorugh" to "through",
                "thnk" to "think",
                "thnaks" to "thanks",
                "todya" to "today",
                "togehter" to "together",
                "togther" to "together",
                "tommorow" to "tomorrow",
                "tommorrow" to "tomorrow",
                "tomorow" to "tomorrow",
                "tothe" to "to the",
                "truely" to "truly",
                "tyep" to "type",
                // u
                "udnerstand" to "understand",
                "unforunately" to "unfortunately",
                "unfortunatly" to "unfortunately",
                "untill" to "until",
                "usualy" to "usually",
                // v
                "veyr" to "very",
                "vrey" to "very",
                // w
                "waht" to "what",
                "wantd" to "wanted",
                "wath" to "what",
                "wehre" to "where",
                "wehn" to "when",
                "whcih" to "which",
                "whih" to "which",
                "wierd" to "weird",
                "wnat" to "want",
                "wnats" to "wants",
                "woud" to "would",
                "woudl" to "would",
                "wouldnt" to "wouldn't",
                "woudnt" to "wouldn't",
                "wriet" to "write",
                "writting" to "writing",
                // y
                "yoru" to "your",
                "youre" to "you're",
                "ypu" to "you",
                "yr" to "your",
            )
            val dupes = pairs.groupingBy { it.first }.eachCount().filter { it.value > 1 }.keys
            check(dupes.isEmpty()) { "Duplicate autocorrect dict keys: $dupes" }
            pairs.toMap()
        }
    }
}
