package com.typlx.keyboard

class EmojiSuggestionHelper {

    fun suggest(word: String, maxResults: Int = 3): List<String> {
        if (word.isBlank()) return emptyList()
        val key = word.lowercase().trimEnd('.', '!', '?', ',', ';', ':')
        return EMOJI_MAP[key]?.take(maxResults) ?: emptyList()
    }

    companion object {
        internal val EMOJI_MAP: Map<String, List<String>> = mapOf(
            // Emotions — positive
            "happy" to listOf("😊", "😄", "🎉"),
            "happiness" to listOf("😊", "😄", "🎉"),
            "joy" to listOf("😄", "🎊", "✨"),
            "excited" to listOf("🎉", "😆", "🚀"),
            "excited!" to listOf("🎉", "😆", "🚀"),
            "awesome" to listOf("🔥", "💯", "🙌"),
            "amazing" to listOf("🤩", "✨", "💫"),
            "wonderful" to listOf("✨", "🌟", "😍"),
            "great" to listOf("👍", "🙌", "💪"),
            "excellent" to listOf("⭐", "💯", "👏"),
            "fantastic" to listOf("🌟", "🎊", "😄"),
            "nice" to listOf("😊", "👍", "✌️"),
            "good" to listOf("👍", "😊", "✅"),
            "perfect" to listOf("💯", "✅", "🎯"),
            "love" to listOf("❤️", "😍", "💕"),
            "loved" to listOf("❤️", "💕", "🥰"),
            "loving" to listOf("❤️", "🥰", "💞"),
            "cute" to listOf("🥰", "😍", "💕"),
            "beautiful" to listOf("😍", "✨", "🌸"),
            "gorgeous" to listOf("😍", "✨", "🌹"),
            "cool" to listOf("😎", "🤙", "👌"),
            "sweet" to listOf("🍬", "😊", "❤️"),
            "fun" to listOf("🎉", "😄", "🎊"),
            "funny" to listOf("😂", "😆", "🤣"),
            "laugh" to listOf("😂", "🤣", "😆"),
            "lol" to listOf("😂", "🤣", "😹"),
            "haha" to listOf("😂", "🤣", "😆"),
            "hehe" to listOf("😄", "😆", "😏"),
            "smile" to listOf("😊", "😁", "🙂"),
            "smiling" to listOf("😊", "😁", "😄"),
            "grin" to listOf("😁", "😄", "😺"),
            "wink" to listOf("😉", "😘", "😏"),
            // Emotions — negative
            "sad" to listOf("😢", "😔", "💔"),
            "unhappy" to listOf("😔", "😟", "😞"),
            "cry" to listOf("😢", "😭", "💧"),
            "crying" to listOf("😭", "😢", "💔"),
            "upset" to listOf("😢", "😡", "💔"),
            "angry" to listOf("😠", "🤬", "💢"),
            "anger" to listOf("😠", "🤬", "💢"),
            "mad" to listOf("😤", "🤬", "💢"),
            "frustrated" to listOf("😤", "🙄", "😩"),
            "annoyed" to listOf("😒", "🙄", "😤"),
            "hate" to listOf("😡", "💔", "🚫"),
            "terrible" to listOf("😱", "💀", "🤢"),
            "horrible" to listOf("😱", "🤢", "💀"),
            "awful" to listOf("😱", "💀", "😤"),
            "scared" to listOf("😱", "😨", "😰"),
            "afraid" to listOf("😱", "😨", "😰"),
            "nervous" to listOf("😬", "😰", "🤞"),
            "anxious" to listOf("😰", "😬", "🤯"),
            "worried" to listOf("😟", "😰", "🤞"),
            "tired" to listOf("😴", "😪", "💤"),
            "exhausted" to listOf("😩", "💤", "😴"),
            "sleepy" to listOf("😴", "💤", "😪"),
            "bored" to listOf("🥱", "😑", "😐"),
            "boring" to listOf("🥱", "😑", "😐"),
            "confused" to listOf("😕", "🤔", "❓"),
            "surprised" to listOf("😮", "😲", "😱"),
            "wow" to listOf("😮", "🤩", "🙌"),
            "shocked" to listOf("😱", "😮", "💀"),
            "sick" to listOf("🤒", "🤧", "😷"),
            "ill" to listOf("🤒", "😷", "🤧"),
            // Celebrations
            "birthday" to listOf("🎂", "🎉", "🎁"),
            "party" to listOf("🎉", "🎊", "🥳"),
            "celebrate" to listOf("🎉", "🥳", "🎊"),
            "celebration" to listOf("🎉", "🥳", "🎊"),
            "congrats" to listOf("🎉", "👏", "🥳"),
            "congratulations" to listOf("🎉", "👏", "🥳"),
            "congratulation" to listOf("🎉", "👏", "🥳"),
            "wedding" to listOf("💒", "💍", "💐"),
            "married" to listOf("💒", "💍", "❤️"),
            "engaged" to listOf("💍", "💕", "🥂"),
            "anniversary" to listOf("💑", "❤️", "🥂"),
            "holiday" to listOf("🎄", "🎉", "✈️"),
            "vacation" to listOf("✈️", "🌴", "🏖️"),
            "christmas" to listOf("🎄", "🎁", "🎅"),
            "xmas" to listOf("🎄", "🎁", "⛄"),
            "halloween" to listOf("🎃", "👻", "🕷️"),
            "thanksgiving" to listOf("🦃", "🍂", "🙏"),
            "newyear" to listOf("🎆", "🥂", "🎊"),
            "valentine" to listOf("❤️", "💝", "🌹"),
            "easter" to listOf("🐣", "🌷", "🥚"),
            "graduation" to listOf("🎓", "🎉", "📚"),
            // Weather
            "sunny" to listOf("☀️", "🌞", "😎"),
            "sun" to listOf("☀️", "🌞", "🌻"),
            "rain" to listOf("🌧️", "☔", "💧"),
            "rainy" to listOf("🌧️", "☔", "🌂"),
            "raining" to listOf("🌧️", "☔", "💦"),
            "snow" to listOf("❄️", "☃️", "🌨️"),
            "snowing" to listOf("❄️", "⛄", "🌨️"),
            "cold" to listOf("🥶", "❄️", "🧣"),
            "hot" to listOf("🔥", "☀️", "🥵"),
            "warm" to listOf("☀️", "😊", "🧡"),
            "wind" to listOf("💨", "🌬️", "🌪️"),
            "windy" to listOf("💨", "🌬️", "🍃"),
            "storm" to listOf("⛈️", "🌩️", "💨"),
            "thunder" to listOf("⛈️", "🌩️", "💥"),
            "fog" to listOf("🌫️", "😶‍🌫️", "🌁"),
            "rainbow" to listOf("🌈", "✨", "😍"),
            "cloudy" to listOf("☁️", "🌤️", "😐"),
            "cloud" to listOf("☁️", "⛅", "🌤️"),
            // Food & drink
            "pizza" to listOf("🍕", "😋", "🤌"),
            "coffee" to listOf("☕", "😊", "💪"),
            "tea" to listOf("🍵", "☕", "😌"),
            "beer" to listOf("🍺", "🍻", "😄"),
            "wine" to listOf("🍷", "🥂", "😊"),
            "cocktail" to listOf("🍹", "🥂", "🎉"),
            "cake" to listOf("🎂", "😋", "🍰"),
            "icecream" to listOf("🍦", "😋", "❤️"),
            "chocolate" to listOf("🍫", "😋", "❤️"),
            "burger" to listOf("🍔", "😋", "🍟"),
            "sushi" to listOf("🍣", "😋", "🐟"),
            "tacos" to listOf("🌮", "😋", "🇲🇽"),
            "pasta" to listOf("🍝", "😋", "🍷"),
            "salad" to listOf("🥗", "😊", "🥦"),
            "breakfast" to listOf("🍳", "☕", "😊"),
            "lunch" to listOf("🥙", "😋", "☕"),
            "dinner" to listOf("🍽️", "😋", "🍷"),
            "hungry" to listOf("😋", "🍽️", "🤤"),
            "delicious" to listOf("😋", "🤌", "👌"),
            "yummy" to listOf("😋", "🤤", "😍"),
            // Fire / heat (spicy)
            "fire" to listOf("🔥", "💥", "😤"),
            "spicy" to listOf("🌶️", "🔥", "😮‍💨"),
            "lit" to listOf("🔥", "💡", "✨"),
            // Activities & sports
            "run" to listOf("🏃", "👟", "💪"),
            "running" to listOf("🏃", "👟", "🏅"),
            "walk" to listOf("🚶", "👟", "😊"),
            "walking" to listOf("🚶", "🌿", "☀️"),
            "swim" to listOf("🏊", "🌊", "💦"),
            "swimming" to listOf("🏊", "🌊", "🏅"),
            "gym" to listOf("💪", "🏋️", "🔥"),
            "workout" to listOf("💪", "🏋️", "🔥"),
            "exercise" to listOf("💪", "🏃", "🔥"),
            "yoga" to listOf("🧘", "☮️", "🌿"),
            "dance" to listOf("💃", "🕺", "🎵"),
            "dancing" to listOf("💃", "🕺", "🎶"),
            "music" to listOf("🎵", "🎶", "🎸"),
            "sing" to listOf("🎤", "🎵", "🎶"),
            "singing" to listOf("🎤", "🎵", "🎶"),
            "game" to listOf("🎮", "👾", "🕹️"),
            "gaming" to listOf("🎮", "🕹️", "👾"),
            "play" to listOf("🎮", "⚽", "🎉"),
            "playing" to listOf("🎮", "⚽", "😄"),
            "travel" to listOf("✈️", "🌍", "🗺️"),
            "traveling" to listOf("✈️", "🌍", "📸"),
            "trip" to listOf("✈️", "🗺️", "📸"),
            "sleep" to listOf("😴", "💤", "🌙"),
            "sleeping" to listOf("😴", "💤", "🌙"),
            "work" to listOf("💼", "💻", "☕"),
            "working" to listOf("💻", "☕", "💪"),
            "meeting" to listOf("💼", "🤝", "📊"),
            "study" to listOf("📚", "✏️", "🎓"),
            "studying" to listOf("📚", "✏️", "☕"),
            "read" to listOf("📖", "📚", "☕"),
            "reading" to listOf("📖", "📚", "😊"),
            "write" to listOf("✍️", "📝", "💡"),
            "writing" to listOf("✍️", "📝", "💻"),
            "cook" to listOf("👨‍🍳", "🍳", "😋"),
            "cooking" to listOf("👨‍🍳", "🍳", "😋"),
            // Nature
            "flower" to listOf("🌸", "🌺", "🌷"),
            "flowers" to listOf("💐", "🌸", "🌺"),
            "tree" to listOf("🌳", "🌲", "🍃"),
            "forest" to listOf("🌲", "🌳", "🦌"),
            "beach" to listOf("🏖️", "🌊", "☀️"),
            "ocean" to listOf("🌊", "🐬", "🏄"),
            "sea" to listOf("🌊", "⛵", "🐚"),
            "mountain" to listOf("⛰️", "🏔️", "🧗"),
            "moon" to listOf("🌙", "⭐", "🌌"),
            "star" to listOf("⭐", "🌟", "✨"),
            "stars" to listOf("⭐", "🌟", "✨"),
            "night" to listOf("🌙", "⭐", "🌃"),
            "morning" to listOf("🌅", "☕", "😊"),
            // Animals
            "dog" to listOf("🐶", "🐕", "❤️"),
            "cat" to listOf("🐱", "😺", "❤️"),
            "puppy" to listOf("🐶", "🥰", "❤️"),
            "kitten" to listOf("🐱", "🥰", "❤️"),
            // Tech
            "code" to listOf("💻", "🖥️", "⌨️"),
            "coding" to listOf("💻", "⌨️", "☕"),
            "bug" to listOf("🐛", "💀", "😅"),
            "launch" to listOf("🚀", "🎉", "🔥"),
            "ship" to listOf("🚢", "🚀", "📦"),
            "shipped" to listOf("🚀", "📦", "🎉"),
            // Miscellaneous
            "thanks" to listOf("🙏", "😊", "❤️"),
            "thank" to listOf("🙏", "😊", "❤️"),
            "please" to listOf("🙏", "😊", "✌️"),
            "sorry" to listOf("🙏", "😢", "💔"),
            "okay" to listOf("👌", "✅", "😊"),
            "ok" to listOf("👌", "✅", "😊"),
            "yes" to listOf("✅", "👍", "😊"),
            "no" to listOf("❌", "👎", "😔"),
            "maybe" to listOf("🤔", "🤷", "😅"),
            "help" to listOf("🙏", "🆘", "💪"),
            "idea" to listOf("💡", "🤔", "✨"),
            "money" to listOf("💰", "💵", "🤑"),
            "win" to listOf("🏆", "🎉", "💪"),
            "winner" to listOf("🏆", "🥇", "🎉"),
            "heart" to listOf("❤️", "💕", "😍"),
            "peace" to listOf("☮️", "🕊️", "✌️"),
            "home" to listOf("🏠", "❤️", "😊"),
            "family" to listOf("👨‍👩‍👧‍👦", "❤️", "🏠"),
            "friend" to listOf("👫", "❤️", "😊"),
            "friends" to listOf("👫", "🤝", "❤️"),
            "success" to listOf("🏆", "🎉", "💪"),
            "fail" to listOf("😔", "💀", "🤦"),
            "oops" to listOf("😅", "🤦", "😬"),
            "whoops" to listOf("😅", "🤦", "😬"),
            "lmao" to listOf("😂", "🤣", "💀"),
            "omg" to listOf("😱", "😮", "🤩"),
            "tbh" to listOf("🤷", "😅", "💬"),
            "imo" to listOf("🤔", "💬", "😊"),
            "friday" to listOf("🎉", "😄", "🍺"),
            "monday" to listOf("😩", "☕", "💼"),
            "weekend" to listOf("🎉", "😊", "🏖️"),
        )
    }
}
